version: "3"
services:
  api-gateway:
    build: "./api-gateway"
    depends_on:
      - a-service
    volumes:
      - ./api-gateway:/opt/app
    ports:
      - 7000:7000

  a-service:
    build: "./a-service"
    depends_on:
      - a-service-db
    volumes:
      - ./a-service:/opt/app
    ports:
      - 7100:7100
    environment:
      - DB_URI=mysql://root:password@a-service-db/db?charset=UTF

  a-service-db:
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MUSQL_DATABASE=db
    image: mysql:5.7.20
    ports:
      - 0.0.0.0:7200:3306
